apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "autotrader.fullname" . }}-config-updater-manual
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    {{- include "autotrader.labels" . | nindent 4 }}
    app.kubernetes.io/component: config-updater
spec:
  template:
    spec:
      serviceAccountName: {{ include "autotrader.fullname" . }}-config-updater
      restartPolicy: OnFailure
      containers:
        - name: config-updater
          image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
          env:
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_SLAVE_STATEFULSET
              value: "{{ include "autotrader.fullname" . }}-slave"
            - name: K8S_CONFIGMAP_BASENAME
              value: "{{ include "autotrader.fullname" . }}-slave-symbols"
            - name: HELM_CHART_NAME
              value: {{ include "autotrader.name" . | quote }}