apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "autotrader.fullname" . }}-slave-kline-websocket
  labels:
    {{- include "autotrader.labels" . | nindent 4 }}
    app.kubernetes.io/component: slave-kline-websocket
spec:
  replicas: {{ .Values.slave.replicaCount }}
  serviceName: {{ include "autotrader.fullname" . }}-slave-kline-websocket
  selector:
    matchLabels:
      {{- include "autotrader.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: slave-kline-websocket
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "autotrader.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: slave-kline-websocket
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "autotrader.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{- range $i, $e := until (int .Values.slave.replicaCount) }}
        - name: symbols-config-{{ $i }}
          configMap:
            name: {{ include "autotrader.fullname" $ }}-slave-symbols-{{ $i }}
      {{- end }}
      containers:
        - name: kline-websocket
          image: "{{ .Values.slave.image.kline_websocket.repository }}:{{ .Values.slave.image.kline_websocket.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.slave.image.kline_websocket.pullPolicy }}
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "autotrader.fullname" . }}-mongodb
                  key: mongo-uri
            {{- range $key, $val := .Values.slave.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts:
          {{- range $i, $e := until (int .Values.slave.replicaCount) }}
            - name: symbols-config-{{ $i }}
              mountPath: /config/{{ $i }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
