version: "3.8"

services:
  app:
    build: .
    environment:
      - CONTROLLER_TYPE=StrategyController
    command: python main.py StrategyController
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
